### ISSUE TITLE
gltriangle.jl not working

### ISSUE THREAD

**Issue by doppioandante** [barche/QmlJuliaExamples#1]
System: Ubuntu 21.04, gnome/wayland, relevant env var: QT_QPA_PLATFORM=xcb

While the QML GUI works, no triangle seems to be rendered:
![Screenshot from 2021-07-13 11-58-49](https://user-images.githubusercontent.com/491850/125432746-55f692e0-934f-4272-bd34-e07ab4368358.png)

I think this could be my system fault, but I would like to debug this.

~Where does the OpenGLViewport object come from? I wanted to look it up but I can't find any reference on the qt docs.~

**Comment by doppioandante** [comment]
Upon further inspection, it seems that the `render` method is never called from the Qt side. Aside, the shader compilation log retrieval is slightly wrong (probably old Julia), I will send a pull request for that.

**Comment by francoislaurent** [comment]
Same here with Xorg instead of Wayland.

The `makie-plot.jl` example suffers a similar issue. `MakieViewport` never calls the function pointed to by the `renderFunction` attribute.

**Comment by ufechner7** [comment]
I tested QML 0.8 with Ubuntu 23.04 on Wayland, and this example works fine.

```
ufechner@vmware-13:~/repos$ julia
...

julia> import LibGit2

julia> isdir("QmlJuliaExamples") || LibGit2.clone("https://github.com/barche/QmlJuliaExamples.git", "QmlJuliaExamples")
LibGit2.GitRepo("/home/ufechner/repos/QmlJuliaExamples")

julia> cd("QmlJuliaExamples/basic") # or images, opengl or plots instead of the basic subdirectory

julia> 
  Downloaded artifact: eudev
...
    Updating `~/repos/QmlJuliaExamples/opengl/Project.toml`
  [1f15a43c] + CxxWrap v0.14.0
  [5789e2e9] + FileIO v1.16.1
⌃ [e9467ef8] + GLMakie v0.6.13
  [5c1252a2] + GeometryBasics v0.4.9
⌅ [ee78f7c6] + Makie v0.17.13
  [66fc600b] + ModernGL v1.1.7
  [510215fc] + Observables v0.5.4
  [2db162a6] + QML v0.8.0
    Updating `~/repos/QmlJuliaExamples/opengl/Manifest.toml`
  [621f4979] + AbstractFFTs v1.5.0
...

Precompiling project...
  207 dependencies successfully precompiled in 142 seconds. 25 already precompiled.
  2 dependencies had warnings during precompilation:
...

julia> include("gltriangle.jl")
```
@barche Please, close this issue.
